apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: admin
    isDefault: true
    editable: true

    secureJsonData:
      password: admin123

    jsonData:
      database: sensors
      sslmode: disable
      postgresVersion: 1500
